kind = "web"
previewPath = "/"
title = "Sistema de Notas"
version = "1.0.0"
id = "artifacts/notas"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22524

[services.development]
run = "pnpm --filter @workspace/notas run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/notas", "run", "build" ]
publicDir = "artifacts/notas/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22524"
BASE_PATH = "/"
